languageCode = "en"
languageName = "English"
weight = 1
# title = "joshuaflores.rocks"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
name = "Joshua Flores"
  image = "img/selfie.jpg"
  headline = "User Experience Designer and Web Developer"
  bio = "User Experience Designer and Web Developer"
  links = [
     { email = "joshuapflores.design@gmail.com" },
     { github = "https://github.com/joshua-flores" },
     { linkedin = "https://www.linkedin.com/in/joshua-flores-18b90516b/" },
     { youtube = "https://www.youtube.com/@joshlearnspiano2928" },
  ]
